### ISSUE TITLE
Binary installation not working 

### ISSUE THREAD

**Issue by BhooshanDeshpande** [danielsnider/follow_waypoints#13]
I used `"sudo apt-get ..."` command to install this package. And it is not running out of the box. 
The files that  I can see in the `/opt/ros/...` location is just 'cmake' folder and package.xml. Also the `roslaunch follow_waypoints` is not producing anything after autocomplete.

**Comment by chugoh** [comment]
I have the same issue, is there any other way that I can do an installation manually?

**Comment by danielsnider** [comment]
Hey @chugoh, yes there should be a way to manually install. I don't have a way to test this right now, but something like this might work. 
```
cd ~/catkin_ws/src
git clone https://github.com/danielsnider/follow_waypoints
cd ~/catkin_ws
catkin_make
source ~/catkin_ws/devel/setup.bash
rosrun follow_waypoints follow_waypoints.py
```
I don't remember if `catkin_make` is a required step or not.
