### ISSUE TITLE
terminal problem

### ISSUE THREAD

**Issue by SeaFu** [danielsnider/follow_waypoints#4]
![vincent vincent _004](https://user-images.githubusercontent.com/42667670/48604479-00687c00-e9b5-11e8-8abe-36ff571e4c05.png)

**Comment by danielsnider** [comment]
Make sure you followed steps 1.1 to 1.4 in the ROS installation
instructions.
http://wiki.ros.org/kinetic/Installation/Ubuntu

If still not working what output do you get if you do this?

```
find /etc/apt/ | grep -i ros
```



Daniel Snider ツ

**Comment by SeaFu** [comment]
It installed successfully,but how can I add path to this roslaunch.It shows can't find the launch file
![turt5254 525-4 _018](https://user-images.githubusercontent.com/42667670/49063708-28789a80-f253-11e8-9afc-821577e528a9.png)

**Comment by danielsnider** [comment]
You should read the documentation page here: http://wiki.ros.org/follow_waypoints

It contains instructions:

## 3. Usage

To set waypoints you can either publish a ROS PoseWithCovarianceStamped message to the /initialpose topic directly or use RViz’s tool "2D Pose Estimate" to click anywhere. To visualize the waypoints as pink arrows in RViz, configure RViz to display the topic /current_waypoints which is published by follow_waypoints and must be subscribed to in Rviz as a PoseAarray type.

To initiate waypoint following send a "path ready" message.

```
$ rostopic pub /path_ready std_msgs/Empty -1
```

To clear the waypoint queue send a "path reset" message.

```
$ rostopic pub /path_reset std_msgs/Empty -1
```

**Comment by SeaFu** [comment]
got it!!!  Thank you very much

**Comment by danielsnider** [comment]
Good job! Way to go! :)
