### ISSUE TITLE
Roslaunch error

### ISSUE THREAD

**Issue by Shubhamvithalani** [danielsnider/follow_waypoints#6]
I have installed using sudo apt and when I tried to launch this on my ROS Kinetic. This error occured.
[follow_waypoints.launch] is neither a launch file in package [follow_waypoints] nor is [follow_waypoints] a launch file name
The traceback for the exception was written to the log file.

**Comment by danielsnider** [comment]
#### 1. Do you see follow_waypoints in the list of installed ROS packages?
On your running system, you can use rospack:
```
rospack list-names | grep follow_waypoints
```
#### 2. Are you sourcing your ROS workspace?
http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment#Create_a_ROS_Workspace

#### 3. What's the full roslaunch command that you are using?

**Comment by danielsnider** [comment]
#### 4. Can you find the installed follow_waypoints code?
```
roscd follow_waypoints
```

**Comment by Shubhamvithalani** [comment]
@danielsnider Thanks for the prompt reply. The issue has been solved. Turns out it was not building properly.

**Comment by family288** [comment]
hello! now I have literally same problem! could you tell me how you solved this..?

**Comment by danielsnider** [comment]
Hi @family22, Can you respond with the answers to my 4 numbered questions above? Good luck!

**Comment by Kanishk598** [comment]
> Hi @family22, Can you respond with the answers to my 4 numbered questions above? Good luck!

I have the same problem of getting this error while trying to launch `follow_waypoints.launch`. I can go into the package using `roscd follow_waypoints`. What should I do next?

**Comment by hsaleem1** [comment]
Hi @danielsnider,

I have got the following output after using roslaunch follow_waypoints follow_waypoints.launch

[ DEBUG ] : Adding state 'GET_PATH' to the state machine.
[ DEBUG ] : State 'GET_PATH' is missing transitions: {}
[ DEBUG ] : TRANSITIONS FOR GET_PATH: {'success': 'FOLLOW_PATH'}
[INFO][139636283606784][/follow_waypoints/__init__:54]: Connecting to move_base...

Could you please guide me, what can I do next?
